#
# Blog Settings
#
author: Malekbenz
description: I'm FullStack Developer
url: https://anem.info
title: anem.info (website)
subtitle: ...website
gravatar_url: http://2.gravatar.com/avatar/8b40bf825a021162659ab478804bff5b"
contents: /dist 
# Github repositoriesname: malekbenz, 
#
# Github repositories
github_user: malekbenz
github_repo_url: https://github.com/malekbenz

# Jekyll Settings
#
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

paginate_path: "page/:num"
category_dir: categories
# Disqus Comments
disqus_short_name: blog-malekbenz-com
disqus_show_comment_count: true
#
plugins: []
exclude: ["README.md","gulpfile.js", "src", "debug.log",node_modules, package.json, npm-debug.log, gulp.js,  bower_components]
include: [".well-known"]

